import type { SiteCopy } from "./types";

export const en: SiteCopy = {
  lang: "en",
  alternateLang: "fr",
  alternateLabel: "FR",
  title: "RealmBox — World of Warcraft locally with AzerothCore and bots",
  description: "Run your own Azeroth on your computer. RealmBox installs AzerothCore, populates the world with Playerbots, and opens WoW from one application.",
  nav: { features: "RealmBox", install: "Install", technology: "Technology", faq: "FAQ", github: "GitHub" },
  hero: {
    eyebrow: "World of Warcraft · entirely local",
    title: "Azeroth at home.",
    accent: "Bots by your side.",
    body: "RealmBox turns your compatible World of Warcraft copy into a local solo adventure: AzerothCore runs the world, Playerbots populate it, and the launcher handles the entire setup.",
    download: "View the 0.5.0 preview",
    availability: "Check GitHub for installer and SHA-256 availability. Windows remains experimental; the full 0.5.0 gameplay path still needs qualification on both platforms.",
    install: "See how to install",
    screenshotAsset: "launcher-ready-en.webp",
    screenshotAlt: "The RealmBox launcher ready to start World of Warcraft locally",
    screenshotCaption: "RealmBox 0.5.0 interface · preview with demonstration data",
  },
  updates: {
    eyebrow: "What’s new · 0.5.0 preview",
    title: "Prepare your world. Choose your pace.",
    body: "A home screen with realm shortcuts and new tools for your solo adventure. These views show version 0.5.0; check the preview release for installer availability.",
    items: [
      { title: "Setup in three steps", body: "Your WoW copy, your companions, then a summary. RealmBox checks Docker and available disk space before allowing the download." },
      { title: "Three progression speeds", body: "Normal, Comfortable, or Accelerated: inspect the values before applying them with the world stopped. Previous rules can be restored; enemy difficulty stays the same." },
      { title: "Find quests and items locally", body: "The Local guide finds up to eight results by name in your world’s catalogue, with their source. No AI or external service, and no access to your character." },
      { title: "More control over your party", body: "Three five-player squad presets, an observed primary companion, and a preview of party or target commands. Recalling the same bots by name is not guaranteed." },
      { title: "Protect your progress", body: "Create a complete, verified backup from Protection. Copies stay on your computer, outside the replaceable installation, without overwriting earlier backups." },
      { title: "Dialogue stays optional", body: "Direct, Immersive, or Lively: adjust conversations independently from population. The new failure-recovery patch depends on server images rebuilt for 0.5.0." },
    ],
    link: { href: "https://github.com/bnjdpn/RealmBox/releases/tag/v0.5.0", label: "Preview changes and availability" },
  },
  promise: {
    eyebrow: "WoW without server administration",
    title: "You play. RealmBox handles the rest.",
    body: "No command line, no database configuration, and no public server to maintain.",
    items: [
      { number: "01", title: "Azeroth runs on your computer", body: "AzerothCore, MySQL, and the game services are installed inside a local Docker environment." },
      { number: "02", title: "The world is populated", body: "Playerbots adds autonomous adventurers and lets you form a balanced party of companions." },
      { number: "03", title: "One button to play", body: "RealmBox starts WoW and every service in the right order, then stops them when the client closes." },
    ],
  },
  companions: {
    eyebrow: "Built-in Playerbots",
    title: "Azeroth is no longer empty when you play alone.",
    body: "Meet bots in the world, form a party of four companions, and direct them through the RealmBox addon inside WoW.",
    points: ["5, 25, 50, 100, or 150 bots, limited by Docker’s assigned memory", "Separate presence: Dispersed, Natural, or Always nearby", "Your in-game party: Escort, Guard, or Free", "Optional dialogue: Direct, Immersive, or Lively"],
    screenshotAsset: "launcher-companions-en.webp",
    screenshotAlt: "Playerbots population settings in RealmBox",
  },
  install: {
    eyebrow: "Guided installation",
    title: "From zero to Azeroth in five steps.",
    intro: "Prepare Docker Desktop and your compatible WoW copy, then follow the 0.5.0 setup assistant. Installers appear on the preview release page when available.",
    steps: [
      {
        title: "Install Docker Desktop",
        body: "Start Docker Desktop and keep it running. RealmBox installs AzerothCore, the local database, and Playerbots inside it.",
        links: [{ href: "https://www.docker.com/products/docker-desktop/", label: "Download Docker Desktop" }],
      },
      {
        title: "Download French or English WoW data",
        body: "RealmBox needs the Data folder from a compatible client. Open the ChromieCraft page in your preferred language, then choose the corresponding client or language pack offered there.",
        links: [
          { href: "https://chromiecraft.com/fr/telechargements/", label: "Client et téléchargements en français" },
          { href: "https://chromiecraft.com/en/downloads/", label: "English client and downloads" },
        ],
      },
      {
        title: "Download RealmBox",
        body: "Check the preview assets for the Apple Silicon Mac DMG or experimental Windows x64 installer. Wait until both the installer and SHA256SUMS.txt are available, then compare the SHA-256 checksum.",
        links: [{ href: "https://github.com/bnjdpn/RealmBox/releases", label: "Open RealmBox Releases" }],
      },
      { title: "Your WoW copy, then your companions", body: "In the assistant, select the game folder or Data, then choose population, presence, and optional dialogue. Game files are checked before you continue." },
      { title: "Install, then play", body: "Review Your installation and resolve Docker or disk warnings. Click Install after the checks pass, then Play when your world is ready." },
    ],
    requirementsTitle: "System requirements",
    requirements: [
      { label: "System", value: "Apple Silicon Mac or Windows x64 PC (experimental)" },
      {
        label: "Containers",
        value: "Docker Desktop installed, running, and assigned memory",
        links: [{ href: "https://www.docker.com/products/docker-desktop/", label: "Docker Desktop" }],
      },
      { label: "Storage", value: "At least 24 GiB free, plus the optional local model" },
      { label: "Game", value: "A complete compatible WoW Data folder" },
      { label: "Network", value: "Internet access for the first installation" },
    ],
    capacityTitle: "Memory assigned to Docker",
    capacities: [
      { memory: "under 12 GiB", bots: "5 bots max" },
      { memory: "12–19 GiB", bots: "50 bots max" },
      { memory: "20–27 GiB", bots: "100 bots max" },
      { memory: "28 GiB or more", bots: "150 bots max" },
    ],
    note: "The first launch prepares local data and can take time. Later launches are much faster.",
  },
  technology: {
    eyebrow: "Under the hood",
    title: "A complete local stack controlled by the launcher.",
    body: "RealmBox is a Tauri and React desktop application. It orchestrates free-software components pinned to immutable versions while keeping server details out of the player flow.",
    nodes: [
      { label: "Your WoW client", detail: "Read-only Data" },
      { label: "RealmBox", detail: "Setup and supervision" },
      { label: "AzerothCore", detail: "Authserver + worldserver" },
      { label: "Playerbots", detail: "Population and companions" },
      { label: "WoW", detail: "OpenWoW or Wow.exe" },
    ],
    facts: [
      { title: "Locally extracted data", body: "maps, vmaps, mmaps, and dbc are produced from your own Data folder." },
      { title: "Isolated services", body: "Game ports stay bound to 127.0.0.1 and MySQL is not exposed on the host." },
      { title: "Protected updates", body: "Complete, verified backups before migrations and on demand in Protection. If a required backup is missing, the operation stops." },
      { title: "Optional dialogue", body: "Ollama and a small local model can power bot replies without cloud access during play. The CanIRun compatibility check sends only CPU, core count, and memory information." },
    ],
  },
  local: {
    eyebrow: "Your data stays with you",
    title: "A personal Azeroth, not a public server.",
    body: "RealmBox creates no remote account and sends no game files. Your world, characters, backups, and logs stay on your computer.",
    points: ["No automatic telemetry", "No MPQ upload", "Ports restricted to localhost", "Redacted shareable diagnostics", "Backups outside the replaceable runtime", "No proprietary data inside RealmBox"],
  },
  faq: {
    eyebrow: "Frequently asked questions",
    title: "The essentials before starting setup.",
    items: [
      { question: "Is version 0.5.0 ready to download?", answer: "The preview release page is public. Check its assets for installer and SHA256SUMS.txt availability. Full macOS and Windows gameplay paths still need qualification for this version; Windows is experimental. Distribution signing and notarization are not provided." },
      { question: "Can I undo a solo profile?", answer: "Yes. With the world stopped, you can restore the previous rules. This does not remove experience, money, or professions already gained, and does not change enemy difficulty." },
      { question: "Does the Local guide track my progress?", answer: "No. It only searches quest and item names in local references. It reads neither your quest log nor your inventory and generates no AI advice." },
      { question: "Is this actually World of Warcraft?", answer: "RealmBox uses the files from a compatible World of Warcraft: Wrath of the Lich King copy and starts a local Azeroth through AzerothCore. RealmBox contains and distributes no proprietary game files." },
      { question: "Do I need a subscription or an online server?", answer: "RealmBox does not connect to official servers and needs no subscription for its local operation. You must still use a game copy you are authorized to own." },
      { question: "What do the bots do?", answer: "Playerbots populates Azeroth with autonomous characters. The RealmBox addon can also gather four bots near you to form a playable party." },
      { question: "Which ChromieCraft download should I choose?", answer: "Use the French or English page for your preferred language. RealmBox then detects the locale actually present in the selected Data folder. On Apple Silicon Macs, it reuses that data with OpenWoW instead of running the Windows Wow.exe." },
      { question: "Does RealmBox modify my WoW folder?", answer: "No. The selected folder is checked and used read-only during extraction. RealmBox-managed files live in its own local directory." },
    ],
  },
  footer: {
    independent: "Independent free-software project, not affiliated with Blizzard Entertainment or ChromieCraft.",
    license: "AGPL-3.0",
    documentation: "Documentation",
    source: "Source code",
    portfolio: "More projects",
  },
};
