[package]
name = "realmbox-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
realmbox-domain = { path = "../realmbox-domain" }
rusqlite.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

