import type { Language } from "./i18n";

const fr = {
  eyebrow: "VOTRE AVENTURE COMMENCE ICI", steps: "Préparation du monde",
  game: "Votre copie de WoW", world: "Vos compagnons", review: "Votre installation",
  gameBody: "Indiquez où se trouve votre jeu. RealmBox s’occupe ensuite du monde local et de son lancement.",
  worldBody: "Choisissez l’ambiance de votre monde. Vous pourrez modifier ces réglages après l’installation.",
  reviewBody: "Tout est réuni ici. Vérifiez vos choix avant de lancer les téléchargements.",
  next: "Continuer", reviewAction: "Vérifier mon installation", edit: "Modifier",
  gameHelp: "Je n’ai pas encore les fichiers de WoW", gameDownload: "Ouvrir les téléchargements ChromieCraft",
  gameHelpBody: "Récupérez une copie compatible 3.3.5a, puis décompressez-la. Sélectionnez le dossier du jeu ou son sous-dossier Data, pas l’archive téléchargée.",
  macHelp: "Sur Mac, les fichiers du client Windows servent de données. RealmBox installe OpenWoW pour lancer le jeu nativement.",
  buildPending: "Archives reconnues. La version exacte sera confirmée pendant l’extraction.",
  selectionFailed: "Ce dossier n’a pas pu être utilisé. Choisissez une copie complète et décompressée de WoW ; le diagnostic précise la cause.",
  login: "Se connecter au jeu", configured: "Population configurée",
  readyInstall: "Prêt à installer", blockedInstall: "Un contrôle nécessite votre attention.",
  noDownload: "Aucun téléchargement ne démarre avant votre confirmation.",
  automatic: "RealmBox s’occupe du reste", automaticBody: "Client géré, monde privé, compte local et addon de compagnons : la préparation est automatique, sans fichier de configuration à éditer.",
  optionalAi: "Facultatif · les bots jouent aussi sans dialogue IA.",
  localAi: "Le modèle reste sur votre ordinateur. Aucun service de dialogue payant n’est activé.",
  prerequisites: "Avant de commencer", checkAgain: "Vérifier à nouveau", checking: "Vérification de cet ordinateur…", checkFailed: "La vérification n’a pas abouti. Réessayez ; rien n’a été installé.",
  computer: "Cet ordinateur", platformHelp: "Mac Apple Silicon ou Windows x64 requis.",
  docker: "Moteur du monde", dockerHelp: "Installez et ouvrez Docker Desktop, puis attendez son démarrage avant de vérifier à nouveau.", dockerLink: "Obtenir Docker Desktop",
  disk: "Espace disponible", required: "requis", unknown: "Non vérifié", attention: "À vérifier", target: "Nouveau royaume", targetBlocked: "Un royaume existe déjà ou l’état est incertain. Fermez cet assistant et consultez le diagnostic ; ne réinstallez pas par-dessus.",
  pendingCheck: "Ces contrôles seront refaits au démarrage de l’installation. La connexion Internet est nécessaire pour les téléchargements.",
  populationLimit: "Limite détectée", bots: "bots", limitHelp: "La limite dépend de la mémoire de Docker. Ce nombre n’est pas un comptage des bots en ligne.",
  setupTime: "La première préparation peut être longue, surtout pour les cartes. Gardez RealmBox ouvert ; la progression suit les étapes réelles, pas un temps estimé.",
  helpFailed: "La page n’a pas pu s’ouvrir. Réessayez depuis le guide d’installation.",
  requested: "Souhaité", planned: "Prévu avec cette mémoire", saved: "Vos réglages restent modifiables", manage: "Votre royaume", manageBody: "L’essentiel, à portée de main.",
  shortcutsBots: "Population & présence", shortcutsSolo: "Rythme de l’aventure", shortcutsBackup: "Protéger ma progression", shortcutsGuide: "Chercher une quête ou un objet",
  installed: "Installé", enabled: "Activés", afterPlay: "Après Jouer, utilisez le compte local ci-dessous pour créer votre personnage.",
  progressBody: "Les fichiers du jeu restent locaux. Le royaume ne devient prêt qu’après vérification de tous les composants.",
  currentStep: "Étape en cours", installationDetail: "Détails de l’installation", prepareData: "Données du jeu", prepareClient: "Client de jeu", prepareWorld: "Monde et compagnons", prepareSave: "Compte et sauvegarde locale", prepareAi: "Dialogue local", prepareFinish: "Vérification finale",
};
type SetupCopy = Record<keyof typeof fr, string>;
const en: SetupCopy = {
  eyebrow: "YOUR ADVENTURE STARTS HERE", steps: "World setup",
  game: "Your copy of WoW", world: "Your companions", review: "Your installation",
  gameBody: "Show us where your game is. RealmBox takes care of the local world and launching it.",
  worldBody: "Choose how your world feels. You can change these settings after installation.",
  reviewBody: "Everything is here. Review your choices before starting any downloads.",
  next: "Continue", reviewAction: "Check my installation", edit: "Edit",
  gameHelp: "I don’t have the WoW files yet", gameDownload: "Open ChromieCraft downloads",
  gameHelpBody: "Get a compatible 3.3.5a copy and extract it. Select the game folder or its Data subfolder, not the downloaded archive.",
  macHelp: "On Mac, the Windows client files provide the data. RealmBox installs OpenWoW to run the game natively.",
  buildPending: "Archives recognized. The exact build will be confirmed during extraction.",
  selectionFailed: "This folder could not be used. Choose a complete, extracted WoW copy; Diagnostics explains the cause.",
  login: "Log in to the game", configured: "Configured population",
  readyInstall: "Ready to install", blockedInstall: "A check needs your attention.",
  noDownload: "No downloads start before you confirm.",
  automatic: "RealmBox takes care of the rest", automaticBody: "Managed client, private world, local account and companion addon: setup is automatic, with no configuration files to edit.",
  optionalAi: "Optional · bots also play without AI dialogue.", localAi: "The model stays on your computer. No paid dialogue service is activated.",
  prerequisites: "Before you begin", checkAgain: "Check again", checking: "Checking this computer…", checkFailed: "The check did not complete. Try again; nothing was installed.",
  computer: "This computer", platformHelp: "Apple Silicon Mac or Windows x64 required.",
  docker: "World engine", dockerHelp: "Install and open Docker Desktop, then wait for it to start before checking again.", dockerLink: "Get Docker Desktop",
  disk: "Available space", required: "required", unknown: "Not verified", attention: "Needs attention", target: "New realm", targetBlocked: "A realm already exists or its state is uncertain. Close this assistant and check Diagnostics; do not reinstall over it.",
  pendingCheck: "Checks run again when installation starts. An internet connection is required for downloads.",
  populationLimit: "Detected limit", bots: "bots", limitHelp: "The limit depends on Docker memory. This is not a count of bots online.",
  setupTime: "First-time setup can take a while, especially the maps. Keep RealmBox open; progress follows real steps, not an estimated duration.",
  helpFailed: "The page could not open. Try again from the installation guide.",
  requested: "Requested", planned: "Planned with this memory", saved: "You can change your settings later", manage: "Your realm", manageBody: "Your essentials, within reach.",
  shortcutsBots: "Population & presence", shortcutsSolo: "Adventure pace", shortcutsBackup: "Protect my progress", shortcutsGuide: "Find a quest or item",
  installed: "Installed", enabled: "Enabled", afterPlay: "After Play, use the local account below to create your character.",
  progressBody: "Game files stay local. The realm is only ready after every required component has been verified.",
  currentStep: "Current step", installationDetail: "Installation details", prepareData: "Game data", prepareClient: "Game client", prepareWorld: "World and companions", prepareSave: "Account and local save", prepareAi: "Local dialogue", prepareFinish: "Final verification",
};
export const setupMessages: Record<Language, SetupCopy> = { fr, en };
